package View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import Model.SQLHandler;
import View.Cart;
import View.Information;
import View.Login;
import java.awt.Image;
import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xtir0
 */
public class Home extends javax.swing.JFrame {
DecimalFormat df = new DecimalFormat("#");
    public SQLHandler sqlHandler = new SQLHandler();
    public DefaultTableModel tableModelProducts = new DefaultTableModel();
    private int id_product, id_customer;
    private String username;
    private int quantity = 0;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setTableProduct();
        if (id_customer == 0) {
            btn_logout.setText("Đăng nhập");
        } else {
            btn_logout.setText("Đăng xuất");
        }
        btn_buy.setVisible(false);

    }

    public Home(int id_customer) {
        initComponents();
        setTableProduct();
        this.id_customer = id_customer;
        if (id_customer == 0) {
            btn_logout.setText("Đăng nhập");
        } else {
            btn_logout.setText("Đăng xuất");
        }
        btn_buy.setVisible(false);

    }

    public void showDataProducts() {
        try {
            ResultSet rs = sqlHandler.getDataProducts();
            int i = 1;
            while (rs.next()) {
                Object[] rows = {
                    i, rs.getString("name_product"), rs.getString("type_product"), df.format(rs.getDouble("price")), rs.getInt("quantity"), rs.getInt("id_product")
                };
                tableModelProducts.addRow(rows);
                i++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void hideColumn(JTable table, int index) {
        table.getColumnModel().getColumn(index).setMinWidth(0);
        table.getColumnModel().getColumn(index).setMaxWidth(0);
        table.getColumnModel().getColumn(0).setMinWidth(40);
        table.getColumnModel().getColumn(0).setMaxWidth(40);
        table.getColumnModel().getColumn(1).setMinWidth(180);
    }

    public void setTableProduct() {
        String columns[] = {
            "STT", "Tên sản phẩm", "Loại", "Giá", "Số lượng còn", "id"
        };
        tableModelProducts.setColumnIdentifiers(columns);
        tbl_products.setModel(tableModelProducts);
        hideColumn(tbl_products, 5);
        showDataProducts();
    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lab_imgproduct.getWidth(), lab_imgproduct.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    public void setLabelProduct() {
        try {
            ResultSet rs = sqlHandler.getDataIdProductId(id_product);
            while (rs.next()) {
                lab_nameproduct1.setText(rs.getString("name_product"));
                lab_type1.setText(rs.getString("type_product"));
                lab_fabric1.setText(rs.getString("fabric"));
                lab_madein1.setText(rs.getString("madein"));
                lab_quantity1.setText(rs.getString("quantity"));
                lab_price1.setText(String.valueOf(df.format(rs.getDouble("price"))));
                lab_imgproduct.setIcon(ResizeImage(rs.getString("urlimg")));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dialog_quantity = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        spinner_quantity = new javax.swing.JSpinner();
        btn_ok = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lab_nameproduct = new javax.swing.JLabel();
        lab_type = new javax.swing.JLabel();
        lab_price = new javax.swing.JLabel();
        lab_madein = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lab_imgproduct = new javax.swing.JLabel();
        lab_fabric = new javax.swing.JLabel();
        lab_quantity = new javax.swing.JLabel();
        lab_quantity1 = new javax.swing.JLabel();
        lab_nameproduct1 = new javax.swing.JLabel();
        lab_type1 = new javax.swing.JLabel();
        lab_madein1 = new javax.swing.JLabel();
        lab_fabric1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lab_price1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_products = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btn_buy = new javax.swing.JButton();
        btn_addcart = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_cart = new javax.swing.JButton();
        btn_profile = new javax.swing.JButton();

        dialog_quantity.setTitle("Số lượng thêm");
        dialog_quantity.setMinimumSize(new java.awt.Dimension(315, 150));

        jPanel5.setBackground(new java.awt.Color(153, 255, 51));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Số lượng: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 60, 0, 0);
        jPanel5.add(jLabel3, gridBagConstraints);

        spinner_quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 18, 0, 0);
        jPanel5.add(spinner_quantity, gridBagConstraints);

        btn_ok.setText("Ok");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 18, 36, 50);
        jPanel5.add(btn_ok, gridBagConstraints);

        javax.swing.GroupLayout dialog_quantityLayout = new javax.swing.GroupLayout(dialog_quantity.getContentPane());
        dialog_quantity.getContentPane().setLayout(dialog_quantityLayout);
        dialog_quantityLayout.setHorizontalGroup(
            dialog_quantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialog_quantityLayout.setVerticalGroup(
            dialog_quantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ");
        setSize(new java.awt.Dimension(930, 600));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Chi tiết sản phẩm");

        lab_nameproduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lab_nameproduct.setText("Tên sản phẩm:");

        lab_type.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lab_type.setText("Loại:");

        lab_price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lab_price.setText("Giá:");

        lab_madein.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lab_madein.setText("Nhập từ:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Chất liệu:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Hình ảnh sản phẩm:");

        lab_imgproduct.setText(" ");

        lab_fabric.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_fabric.setText(" ");

        lab_quantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lab_quantity.setText("Số lượng còn: ");

        lab_quantity1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_quantity1.setText("        ");

        lab_nameproduct1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_nameproduct1.setText("        ");

        lab_type1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_type1.setText("        ");

        lab_madein1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_madein1.setText("        ");

        lab_fabric1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_fabric1.setText("        ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("        ");

        lab_price1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_price1.setText("        ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(lab_fabric1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lab_quantity)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lab_quantity1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lab_fabric)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lab_price)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lab_price1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lab_nameproduct)
                        .addGap(18, 18, 18)
                        .addComponent(lab_nameproduct1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lab_type)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab_type1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lab_madein)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lab_madein1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lab_imgproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_nameproduct)
                    .addComponent(lab_nameproduct1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_type)
                    .addComponent(lab_madein)
                    .addComponent(lab_type1)
                    .addComponent(lab_madein1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lab_fabric)
                    .addComponent(lab_fabric1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_quantity)
                    .addComponent(lab_quantity1)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_price)
                    .addComponent(lab_price1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab_imgproduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sản phẩm");

        tbl_products.setBackground(new java.awt.Color(153, 255, 255));
        tbl_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_products);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));

        btn_buy.setBackground(new java.awt.Color(255, 153, 51));
        btn_buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_buy.setText("Mua");
        btn_buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buyActionPerformed(evt);
            }
        });

        btn_addcart.setBackground(new java.awt.Color(102, 255, 102));
        btn_addcart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_addcart.setText("Thêm vào giỏ hàng");
        btn_addcart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addcartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btn_addcart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_buy, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addcart)
                    .addComponent(btn_buy))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Shop bán quần áo");

        btn_logout.setBackground(new java.awt.Color(255, 51, 51));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_logout.setText("Đăng xuất");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_cart.setBackground(new java.awt.Color(204, 255, 0));
        btn_cart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cart.setText("Giỏ hàng của tôi");
        btn_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cartActionPerformed(evt);
            }
        });

        btn_profile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_profile.setText("Thông tin cá nhân");
        btn_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cart)
                .addGap(18, 18, 18)
                .addComponent(btn_profile)
                .addGap(18, 18, 18)
                .addComponent(btn_logout)
                .addContainerGap())
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cart)
                    .addComponent(btn_logout)
                    .addComponent(btn_profile)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productsMouseClicked
        // TODO add your handling code here:
        int row = tbl_products.getSelectedRow();
        id_product = Integer.valueOf(tbl_products.getModel().getValueAt(row, 5).toString());
        setLabelProduct();
    }//GEN-LAST:event_tbl_productsMouseClicked

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        if (username != null) {
            username = null;
            this.dispose();
            new Login().setVisible(true);
        } else {
            this.dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cartActionPerformed
        // TODO add your handling code here:
        if (id_customer == 0) {
            JOptionPane.showMessageDialog(rootPane, "Chưa Đăng nhập!!!");
        } else {
            this.dispose();
            new Cart(id_customer).setVisible(true);
        }

    }//GEN-LAST:event_btn_cartActionPerformed

    private void btn_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profileActionPerformed
        // TODO add your handling code here:
        if (id_customer == 0) {
            JOptionPane.showMessageDialog(rootPane, "Chưa Đăng nhập!!!");
        } else {
            this.dispose();
            new Information(id_customer).setVisible(true);
        }

    }//GEN-LAST:event_btn_profileActionPerformed

    private void btn_addcartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addcartActionPerformed
        // TODO add your handling code here:
        if (id_customer == 0) {
            JOptionPane.showMessageDialog(rootPane, "Chưa Đăng nhập!!!");
        } else {
            if (id_product == 0) {
                JOptionPane.showMessageDialog(rootPane, "Chưa chọn sản phẩm!!!");
            } else {
                dialog_quantity.setVisible(true);
                dialog_quantity.setLocationRelativeTo(null);
            }

        }


    }//GEN-LAST:event_btn_addcartActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // TODO add your handling code here:
        quantity = (int) spinner_quantity.getValue();
        sqlHandler.addProducttoCart(id_customer, id_product, quantity);
        dialog_quantity.setVisible(false);
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buyActionPerformed
        // TODO add your handling code here:
        if (id_customer == 0) {
            JOptionPane.showMessageDialog(rootPane, "Chưa Đăng nhập!!!");
        } else {
//            this.dispose();
//            new Information(id_customer).setVisible(true);
        }
    }//GEN-LAST:event_btn_buyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addcart;
    private javax.swing.JButton btn_buy;
    private javax.swing.JButton btn_cart;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_profile;
    private javax.swing.JDialog dialog_quantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_fabric;
    private javax.swing.JLabel lab_fabric1;
    private javax.swing.JLabel lab_imgproduct;
    private javax.swing.JLabel lab_madein;
    private javax.swing.JLabel lab_madein1;
    private javax.swing.JLabel lab_nameproduct;
    private javax.swing.JLabel lab_nameproduct1;
    private javax.swing.JLabel lab_price;
    private javax.swing.JLabel lab_price1;
    private javax.swing.JLabel lab_quantity;
    private javax.swing.JLabel lab_quantity1;
    private javax.swing.JLabel lab_type;
    private javax.swing.JLabel lab_type1;
    private javax.swing.JSpinner spinner_quantity;
    private javax.swing.JTable tbl_products;
    // End of variables declaration//GEN-END:variables
}
