package View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import Model.SQLHandler;
import View.Cart;
import View.Information;
import View.Login;
import java.awt.Image;
import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xtir0
 */
public class Home extends javax.swing.JFrame {

    DecimalFormat df55 = new DecimalFormat("#");
    public SQLHandler sqlHandler55 = new SQLHandler();
    public DefaultTableModel tableModelProducts55 = new DefaultTableModel();
    private int id_product55, id_customer55;
    private String username55;
    private int quantity55 = 0, quantitypay55 = 0;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setTableProduct();
        if (id_customer55 == 0) {
            btn_logout.setText("Đăng nhập");
        } else {
            btn_logout.setText("Đăng xuất");
        }

    }

    public Home(int id_customer55) {
        initComponents();
        setTableProduct();
        this.id_customer55 = id_customer55;
        if (id_customer55 == 0) {
            btn_logout.setText("Đăng nhập");
        } else {
            btn_logout.setText("Đăng xuất");
        }

    }

    public void showDataProducts() {
        try {
            ResultSet rs = sqlHandler55.getDataProducts();
            int i = 1;
            while (rs.next()) {
                Object[] rows = {
                    i, rs.getString("name_product"), rs.getString("type_product"), df55.format(rs.getDouble("price")), rs.getInt("quantity"), rs.getInt("id_product")
                };
                tableModelProducts55.addRow(rows);
                i++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void hideColumn(JTable table, int index) {
        table.getColumnModel().getColumn(index).setMinWidth(0);
        table.getColumnModel().getColumn(index).setMaxWidth(0);
        table.getColumnModel().getColumn(0).setMinWidth(40);
        table.getColumnModel().getColumn(0).setMaxWidth(40);
        table.getColumnModel().getColumn(1).setMinWidth(180);
    }

    public void setTableProduct() {
        String columns[] = {
            "STT", "Tên sản phẩm", "Loại", "Giá", "Số lượng còn", "id"
        };
        tableModelProducts55.setColumnIdentifiers(columns);
        tbl_products55.setModel(tableModelProducts55);
        hideColumn(tbl_products55, 5);
        showDataProducts();
    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lab_imgproduct55.getWidth(), lab_imgproduct55.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    public void setLabelProduct() {
        try {
            ResultSet rs = sqlHandler55.getDataIdProductId(id_product55);
            while (rs.next()) {
                lab_nameproduct55.setText(rs.getString("name_product"));
                lab_type55.setText(rs.getString("type_product"));
                lab_fabric55.setText(rs.getString("fabric"));
                lab_madein55.setText(rs.getString("madein"));
                lab_quantity55.setText(rs.getString("quantity"));
                lab_price55.setText(String.valueOf(df55.format(rs.getDouble("price"))));
                lab_imgproduct55.setIcon(ResizeImage(rs.getString("urlimg")));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dialog_quantity = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        spinner_quantity55 = new javax.swing.JSpinner();
        btn_ok55 = new javax.swing.JButton();
        dialog_quantitypay = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        spinner_quantitypay55 = new javax.swing.JSpinner();
        btn_okpay55 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lab_nameproduct = new javax.swing.JLabel();
        lab_type = new javax.swing.JLabel();
        lab_price = new javax.swing.JLabel();
        lab_madein = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lab_imgproduct55 = new javax.swing.JLabel();
        lab_fabric = new javax.swing.JLabel();
        lab_quantity = new javax.swing.JLabel();
        lab_quantity55 = new javax.swing.JLabel();
        lab_nameproduct55 = new javax.swing.JLabel();
        lab_type55 = new javax.swing.JLabel();
        lab_madein55 = new javax.swing.JLabel();
        lab_fabric55 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lab_price55 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_products55 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btn_buy55 = new javax.swing.JButton();
        btn_addcart55 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_cart55 = new javax.swing.JButton();
        btn_profile55 = new javax.swing.JButton();

        dialog_quantity.setTitle("Số lượng thêm");
        dialog_quantity.setMinimumSize(new java.awt.Dimension(315, 150));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Số lượng: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 60, 0, 0);
        jPanel5.add(jLabel3, gridBagConstraints);

        spinner_quantity55.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 18, 0, 0);
        jPanel5.add(spinner_quantity55, gridBagConstraints);

        btn_ok55.setBackground(new java.awt.Color(51, 255, 0));
        btn_ok55.setText("Ok");
        btn_ok55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ok55ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 18, 36, 50);
        jPanel5.add(btn_ok55, gridBagConstraints);

        javax.swing.GroupLayout dialog_quantityLayout = new javax.swing.GroupLayout(dialog_quantity.getContentPane());
        dialog_quantity.getContentPane().setLayout(dialog_quantityLayout);
        dialog_quantityLayout.setHorizontalGroup(
            dialog_quantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialog_quantityLayout.setVerticalGroup(
            dialog_quantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialog_quantitypay.setMinimumSize(new java.awt.Dimension(315, 150));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Số lượng: ");

        btn_okpay55.setBackground(new java.awt.Color(51, 255, 0));
        btn_okpay55.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_okpay55.setText("Ok");
        btn_okpay55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okpay55ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(spinner_quantitypay55, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_okpay55)
                .addGap(43, 43, 43))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinner_quantitypay55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btn_okpay55))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialog_quantitypayLayout = new javax.swing.GroupLayout(dialog_quantitypay.getContentPane());
        dialog_quantitypay.getContentPane().setLayout(dialog_quantitypayLayout);
        dialog_quantitypayLayout.setHorizontalGroup(
            dialog_quantitypayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialog_quantitypayLayout.setVerticalGroup(
            dialog_quantitypayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ");
        setSize(new java.awt.Dimension(930, 600));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Chi tiết sản phẩm");

        lab_nameproduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lab_nameproduct.setText("Tên sản phẩm:");

        lab_type.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lab_type.setText("Loại:");

        lab_price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lab_price.setText("Giá:");

        lab_madein.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lab_madein.setText("Nhập từ:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Chất liệu:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Hình ảnh sản phẩm:");

        lab_imgproduct55.setText(" ");

        lab_fabric.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_fabric.setText(" ");

        lab_quantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lab_quantity.setText("Số lượng còn: ");

        lab_quantity55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_quantity55.setText("        ");

        lab_nameproduct55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_nameproduct55.setText("        ");

        lab_type55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_type55.setText("        ");

        lab_madein55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_madein55.setText("        ");

        lab_fabric55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_fabric55.setText("        ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("        ");

        lab_price55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_price55.setText("        ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(lab_fabric55, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lab_quantity)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lab_quantity55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lab_fabric)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lab_price)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lab_price55, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lab_nameproduct)
                        .addGap(18, 18, 18)
                        .addComponent(lab_nameproduct55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lab_type)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab_type55, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lab_madein)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lab_madein55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lab_imgproduct55, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_nameproduct)
                    .addComponent(lab_nameproduct55))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_type)
                    .addComponent(lab_madein)
                    .addComponent(lab_type55)
                    .addComponent(lab_madein55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lab_fabric)
                    .addComponent(lab_fabric55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_quantity)
                    .addComponent(lab_quantity55)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_price)
                    .addComponent(lab_price55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab_imgproduct55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sản phẩm");

        tbl_products55.setBackground(new java.awt.Color(153, 255, 255));
        tbl_products55.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_products55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_products55MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_products55);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));

        btn_buy55.setBackground(new java.awt.Color(255, 153, 51));
        btn_buy55.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_buy55.setText("Mua");
        btn_buy55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buy55ActionPerformed(evt);
            }
        });

        btn_addcart55.setBackground(new java.awt.Color(102, 255, 102));
        btn_addcart55.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_addcart55.setText("Thêm vào giỏ hàng");
        btn_addcart55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addcart55ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btn_addcart55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_buy55, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addcart55)
                    .addComponent(btn_buy55))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Shop bán quần áo");

        btn_logout.setBackground(new java.awt.Color(255, 51, 51));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_logout.setText("Đăng xuất");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_cart55.setBackground(new java.awt.Color(204, 255, 0));
        btn_cart55.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cart55.setText("Giỏ hàng của tôi");
        btn_cart55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cart55ActionPerformed(evt);
            }
        });

        btn_profile55.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_profile55.setText("Thông tin cá nhân");
        btn_profile55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profile55ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cart55)
                .addGap(18, 18, 18)
                .addComponent(btn_profile55)
                .addGap(18, 18, 18)
                .addComponent(btn_logout)
                .addContainerGap())
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cart55)
                    .addComponent(btn_logout)
                    .addComponent(btn_profile55)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_products55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_products55MouseClicked
        // TODO add your handling code here:
        int row = tbl_products55.getSelectedRow();
        id_product55 = Integer.valueOf(tbl_products55.getModel().getValueAt(row, 5).toString());
        setLabelProduct();
    }//GEN-LAST:event_tbl_products55MouseClicked

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        if (username55 != null) {
            username55 = null;
            this.dispose();
            new Login().setVisible(true);
        } else {
            this.dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_cart55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cart55ActionPerformed
        // TODO add your handling code here:
        if (id_customer55 == 0) {
            JOptionPane.showMessageDialog(rootPane, "Chưa Đăng nhập!!!");
        } else {
            this.dispose();
            new Cart(id_customer55).setVisible(true);
        }

    }//GEN-LAST:event_btn_cart55ActionPerformed

    private void btn_profile55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profile55ActionPerformed
        // TODO add your handling code here:
        if (id_customer55 == 0) {
            JOptionPane.showMessageDialog(rootPane, "Chưa Đăng nhập!!!");
        } else {
            this.dispose();
            new Information(id_customer55).setVisible(true);
        }

    }//GEN-LAST:event_btn_profile55ActionPerformed

    private void btn_addcart55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addcart55ActionPerformed
        // TODO add your handling code here:
        if (id_customer55 == 0) {
            JOptionPane.showMessageDialog(rootPane, "Chưa Đăng nhập!!!");
        } else {
            if (id_product55 == 0) {
                JOptionPane.showMessageDialog(rootPane, "Chưa chọn sản phẩm!!!");
            } else {
                dialog_quantity.setVisible(true);
                dialog_quantity.setLocationRelativeTo(null);
            }

        }
    }//GEN-LAST:event_btn_addcart55ActionPerformed

    private void btn_ok55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ok55ActionPerformed
        // TODO add your handling code here:
        quantity55 = (int) spinner_quantity55.getValue();
        sqlHandler55.addProducttoCart(id_customer55, id_product55, quantity55);
        dialog_quantity.setVisible(false);
    }//GEN-LAST:event_btn_ok55ActionPerformed

    private void btn_buy55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buy55ActionPerformed
        // TODO add your handling code here:
        if (id_customer55 == 0) {
            JOptionPane.showMessageDialog(rootPane, "Chưa Đăng nhập!!!");
        } else {
            if (id_product55 == 0) {
                JOptionPane.showMessageDialog(rootPane, "Chưa chọn sản phẩm!!!");
            } else {
                dialog_quantitypay.setVisible(true);
                dialog_quantitypay.setLocationRelativeTo(null);

            }
        }
    }//GEN-LAST:event_btn_buy55ActionPerformed

    private void btn_okpay55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okpay55ActionPerformed
        // TODO add your handling code here:
        quantitypay55 = (int) spinner_quantitypay55.getValue();
        dialog_quantity.setVisible(false);
        this.dispose();
        new Pay(id_customer55, id_product55, quantitypay55).setVisible(true);
    }//GEN-LAST:event_btn_okpay55ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addcart55;
    private javax.swing.JButton btn_buy55;
    private javax.swing.JButton btn_cart55;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_ok55;
    private javax.swing.JButton btn_okpay55;
    private javax.swing.JButton btn_profile55;
    private javax.swing.JDialog dialog_quantity;
    private javax.swing.JDialog dialog_quantitypay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_fabric;
    private javax.swing.JLabel lab_fabric55;
    private javax.swing.JLabel lab_imgproduct55;
    private javax.swing.JLabel lab_madein;
    private javax.swing.JLabel lab_madein55;
    private javax.swing.JLabel lab_nameproduct;
    private javax.swing.JLabel lab_nameproduct55;
    private javax.swing.JLabel lab_price;
    private javax.swing.JLabel lab_price55;
    private javax.swing.JLabel lab_quantity;
    private javax.swing.JLabel lab_quantity55;
    private javax.swing.JLabel lab_type;
    private javax.swing.JLabel lab_type55;
    private javax.swing.JSpinner spinner_quantity55;
    private javax.swing.JSpinner spinner_quantitypay55;
    private javax.swing.JTable tbl_products55;
    // End of variables declaration//GEN-END:variables
}
