/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.SQLHandler;
import javax.swing.JOptionPane;

/**
 *
 * @author xtir0
 */
public class Login extends javax.swing.JFrame {

    public final SQLHandler sqlHandler = new SQLHandler();

    /**
     * Creates new form Login1
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lb_login_26 = new javax.swing.JLabel();
        lb_user_26 = new javax.swing.JLabel();
        lb_pass_26 = new javax.swing.JLabel();
        textf_user_26 = new javax.swing.JTextField();
        textf_pass_26 = new javax.swing.JTextField();
        btn_login_26 = new javax.swing.JButton();
        btn_signup_26 = new javax.swing.JButton();
        lb_note_26 = new javax.swing.JLabel();
        btn_home_26 = new javax.swing.JButton();
        jlb_26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");

        lb_login_26.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lb_login_26.setForeground(new java.awt.Color(204, 0, 153));
        lb_login_26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_login_26.setText("Đăng nhập");

        lb_user_26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_user_26.setText("Username:");

        lb_pass_26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_pass_26.setText("Password:");

        btn_login_26.setBackground(new java.awt.Color(204, 0, 153));
        btn_login_26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_login_26.setForeground(new java.awt.Color(255, 255, 255));
        btn_login_26.setText("Đăng nhập");
        btn_login_26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login_26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_26ActionPerformed(evt);
            }
        });

        btn_signup_26.setBackground(new java.awt.Color(204, 0, 153));
        btn_signup_26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_signup_26.setForeground(new java.awt.Color(255, 255, 255));
        btn_signup_26.setText("Đăng ký");
        btn_signup_26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signup_26ActionPerformed(evt);
            }
        });

        lb_note_26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_note_26.setText("Bạn chưa có tài khoản?");

        btn_home_26.setBackground(new java.awt.Color(204, 0, 153));
        btn_home_26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_home_26.setForeground(new java.awt.Color(255, 255, 255));
        btn_home_26.setText("Trang chủ");
        btn_home_26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home_26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_home_26ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_login_26, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_user_26)
                                            .addComponent(lb_pass_26))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textf_pass_26, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                            .addComponent(textf_user_26)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lb_note_26)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_signup_26))
                                    .addComponent(btn_login_26, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btn_home_26)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lb_login_26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_user_26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textf_user_26, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_pass_26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textf_pass_26, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addComponent(btn_login_26, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_signup_26, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_note_26))
                .addGap(18, 18, 18)
                .addComponent(btn_home_26, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlb_26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlb_26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlb_26, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_login_26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_26ActionPerformed
        // TODO add your handling code here:
        try {
            if (sqlHandler.getIdCustomer(textf_user_26.getText(), textf_pass_26.getText()) != 0) {
                this.dispose();
                new Home(sqlHandler.getIdCustomer(textf_user_26.getText(), textf_pass_26.getText())).setVisible(true);
            } else if (sqlHandler.getIdEmployee(textf_user_26.getText(), textf_pass_26.getText()) != 0) {
                this.dispose();
                new Manager(sqlHandler.getIdEmployee(textf_user_26.getText(), textf_pass_26.getText())).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Đăng nhập thất bại");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_login_26ActionPerformed

    private void btn_signup_26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signup_26ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new SignUp().setVisible(true);
    }//GEN-LAST:event_btn_signup_26ActionPerformed

    private void btn_home_26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_home_26ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_btn_home_26ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_home_26;
    private javax.swing.JButton btn_login_26;
    private javax.swing.JButton btn_signup_26;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlb_26;
    private javax.swing.JLabel lb_login_26;
    private javax.swing.JLabel lb_note_26;
    private javax.swing.JLabel lb_pass_26;
    private javax.swing.JLabel lb_user_26;
    private javax.swing.JTextField textf_pass_26;
    private javax.swing.JTextField textf_user_26;
    // End of variables declaration//GEN-END:variables
}
