/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.SQLHandler;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author xtir0
 */
public class SignUp extends javax.swing.JFrame {

    public final SQLHandler sqlHandler = new SQLHandler();
    private String username_26, password_26, firstname_26, lastname_26, phone_26, email_26;
    private int gender_26;

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    public void getDataInput() {
        username_26 = textf_user_26.getText();
        password_26 = textf_pass_26.getText();
        firstname_26 = textf_first_26.getText();
        lastname_26 = textf_lastn_26.getText();
        phone_26 = textf_phone_26.getText();
        email_26 = textf_email_26.getText();
        if (rbtn_male_26.isSelected()) {
            gender_26 = 1;
        }
        if (rbtn_female_26.isSelected()) {
            gender_26 = 0;
        }
    }

    public void clearDataInput() {
        textf_user_26.setText("");
        textf_pass_26.setText("");
        textf_first_26.setText("");
        textf_lastn_26.setText("");
        textf_phone_26.setText("");
        textf_email_26.setText("");
        rbtn_female_26.setSelected(false);
        rbtn_male_26.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_groupgender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lb_signup_26 = new javax.swing.JLabel();
        lb_note_26 = new javax.swing.JLabel();
        lb_gender_26 = new javax.swing.JLabel();
        btn_login_26 = new javax.swing.JButton();
        textf_user_26 = new javax.swing.JTextField();
        textf_pass_26 = new javax.swing.JTextField();
        textf_first_26 = new javax.swing.JTextField();
        textf_lastn_26 = new javax.swing.JTextField();
        lb_email_26 = new javax.swing.JLabel();
        textf_phone_26 = new javax.swing.JTextField();
        lb_phone_26 = new javax.swing.JLabel();
        textf_email_26 = new javax.swing.JTextField();
        lb_name_26 = new javax.swing.JLabel();
        rbtn_male_26 = new javax.swing.JRadioButton();
        lb_pass_26 = new javax.swing.JLabel();
        rbtn_female_26 = new javax.swing.JRadioButton();
        lb_firt_26 = new javax.swing.JLabel();
        btn_signup_26 = new javax.swing.JButton();
        lb_lastN_26 = new javax.swing.JLabel();
        lab_notice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng kí");

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        lb_signup_26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_signup_26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_signup_26.setText("Đăng ký");

        lb_note_26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_note_26.setText("Bạn đã có tài khoản?");

        lb_gender_26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_gender_26.setText("Giới tính:");

        btn_login_26.setBackground(new java.awt.Color(255, 255, 102));
        btn_login_26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_login_26.setText("Đăng nhập");
        btn_login_26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_26ActionPerformed(evt);
            }
        });

        lb_email_26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_email_26.setText("Email:");

        lb_phone_26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_phone_26.setText("Số điện thoại:");

        lb_name_26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_name_26.setText("Tên đăng nhập:");

        btn_groupgender.add(rbtn_male_26);
        rbtn_male_26.setText("Nam");

        lb_pass_26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_pass_26.setText("Mật khẩu:");

        btn_groupgender.add(rbtn_female_26);
        rbtn_female_26.setText("Nữ");

        lb_firt_26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_firt_26.setText("Họ:");

        btn_signup_26.setBackground(new java.awt.Color(102, 255, 204));
        btn_signup_26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_signup_26.setText("Đăng ký");
        btn_signup_26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signup_26ActionPerformed(evt);
            }
        });

        lb_lastN_26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_lastN_26.setText("Tên:");

        lab_notice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_notice.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lab_notice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_signup_26, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lb_name_26)
                        .addGap(30, 30, 30)
                        .addComponent(textf_user_26, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(lb_pass_26)
                        .addGap(30, 30, 30)
                        .addComponent(textf_pass_26, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(lb_firt_26)
                        .addGap(30, 30, 30)
                        .addComponent(textf_first_26, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lb_lastN_26)
                        .addGap(30, 30, 30)
                        .addComponent(textf_lastn_26, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lb_gender_26)
                        .addGap(30, 30, 30)
                        .addComponent(rbtn_male_26)
                        .addGap(36, 36, 36)
                        .addComponent(rbtn_female_26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lb_phone_26)
                        .addGap(27, 27, 27)
                        .addComponent(textf_phone_26, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(lb_email_26)
                        .addGap(18, 18, 18)
                        .addComponent(textf_email_26, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(btn_signup_26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lb_note_26)
                        .addGap(18, 18, 18)
                        .addComponent(btn_login_26)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lb_signup_26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab_notice)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_name_26)
                    .addComponent(textf_user_26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_pass_26)
                    .addComponent(textf_pass_26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_firt_26)
                    .addComponent(textf_first_26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_lastN_26)
                    .addComponent(textf_lastn_26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lb_gender_26))
                    .addComponent(rbtn_male_26)
                    .addComponent(rbtn_female_26))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_phone_26)
                    .addComponent(textf_phone_26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_email_26)
                    .addComponent(textf_email_26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(btn_signup_26)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lb_note_26))
                    .addComponent(btn_login_26)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_login_26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_26ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btn_login_26ActionPerformed

    private void btn_signup_26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signup_26ActionPerformed
        // TODO add your handling code here:
        getDataInput();
        try {
            if (sqlHandler.checksignin(username_26) != 0) {
                JOptionPane.showMessageDialog(rootPane, "Đã tồn tại tài tên đăng nhập!!!");
            } else {
                sqlHandler.signUpCustomer(username_26, password_26, firstname_26, lastname_26, phone_26, email_26, gender_26);
                clearDataInput();
                lab_notice.setForeground(Color.black);
                JOptionPane.showMessageDialog(rootPane, "Đăng kí thành công!!!");
                this.dispose();
                new Login().setVisible(true);
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_signup_26ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn_groupgender;
    private javax.swing.JButton btn_login_26;
    private javax.swing.JButton btn_signup_26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lab_notice;
    private javax.swing.JLabel lb_email_26;
    private javax.swing.JLabel lb_firt_26;
    private javax.swing.JLabel lb_gender_26;
    private javax.swing.JLabel lb_lastN_26;
    private javax.swing.JLabel lb_name_26;
    private javax.swing.JLabel lb_note_26;
    private javax.swing.JLabel lb_pass_26;
    private javax.swing.JLabel lb_phone_26;
    private javax.swing.JLabel lb_signup_26;
    private javax.swing.JRadioButton rbtn_female_26;
    private javax.swing.JRadioButton rbtn_male_26;
    private javax.swing.JTextField textf_email_26;
    private javax.swing.JTextField textf_first_26;
    private javax.swing.JTextField textf_lastn_26;
    private javax.swing.JTextField textf_pass_26;
    private javax.swing.JTextField textf_phone_26;
    private javax.swing.JTextField textf_user_26;
    // End of variables declaration//GEN-END:variables
}
